name: PiggyToggle
main: net.loadingchunks.plugins.PiggyToggle.PiggyToggle.PiggyToggle
version: 0.1

commands:
   pvp:
      description: Toggles your PvP Flag
      usage: /pvp
   pt:
   	  description: Manages PiggyToggle Worlds
   	  usage:
   	    - /pt <add/remove> <world>
        - /pt reload